#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: rockchip

permissions: write-all
#ÂºÄÂêØÂÜôÊùÉÈôêÔºåÈò≤Ê≠¢Êó†Ê≥ï‰∏ä‰º†Âà∞release

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
   - cron: 0 20 * * 2
        # ÂàÜ,Êó∂,Êó•,Êúà,Âë®„ÄÇÊØèÂë® ‰∏â 20Êó∂ÊâßË°å‰∏ÄÊ¨° (UTCÊó∂Èó¥)
  
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  FREE_DISK_SH: scripts/free_disk_space.sh
  ENV_SH: scripts/environment.sh
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  # ‰øÆÊîπ REPO_BRANCH Êù•ËææÂà∞Êõ¥ÊîπÁºñËØëÁâàÊú¨
  PLATFORM_FILE: configs/Target-rockchip.txt
  CONFIG_FILE: configs/Packages-L.txt
  CONFIG_5G: configs/Packages-5G.txt
  SETTINGS_SH: scripts/init-settings.sh
  PACKAGES_SH: scripts/packages.sh
  INSTALL5G_SH: scripts/install-5G.sh
  CLASH_CORE_SH: scripts/preset-clash-core-arm64-L.sh
  RUST_SH: scripts/rust.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Ê£ÄÊü•‰ª£Á†Å
      uses: actions/checkout@main

    - name: Ê£ÄÊµã /dev/sda1 ÂàÜÂå∫ÊòØÂê¶Â≠òÂú®ÔºàOverlayÈÉ®ÂàÜÔºâ
      id: overlay
      run: |
        if [ ! -b /dev/sda1 ]; then
          echo "ÈîôËØØÔºö/dev/sda1 ÂàÜÂå∫‰∏çÂ≠òÂú®ÔºåÊó†Ê≥ïÁªßÁª≠ÊâßË°å OverlayFS Áõ∏ÂÖ≥Êìç‰ΩúÔºåÈÄÄÂá∫ ActionsÔºÅ"
          exit 1  # ÈÄÄÂá∫Âπ∂Ê†áËÆ∞ Actions ÊâßË°åÂ§±Ë¥•
        fi
          echo "ÊàêÂäüÊ£ÄÊµãÂà∞ /dev/sda1 ÂàÜÂå∫ÔºåÁªßÁª≠ÊâßË°åÂêéÁª≠Ê≠•È™§„ÄÇ"

    - name: ÂàùÂßãÂåñÁéØÂ¢É
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        chmod +x $FREE_DISK_SH && $FREE_DISK_SH
        sudo -E apt-get -qq update -y
        sudo -E apt-get -qq full-upgrade -y
        chmod +x $ENV_SH && $ENV_SH
        sudo rm -rf /etc/apt/sources.list.d/*
        sudo rm -rf /var/lib/apt/lists/*
        # ËÆæÁΩÆÊó∂Âå∫
        sudo timedatectl set-timezone "$TZ"

    - name: Ê£ÄÊü•Á©∫Èó¥‰ΩøÁî®ÊÉÖÂÜµÔºàÊ∏ÖÁêÜÊÉÖÂÜµÔºâ
      if: (!cancelled())
      run: df -hT

    - name: ÂàõÂª∫ OverlayFS ÁõÆÂΩïÁªìÊûÑÔºàOverlayÈÉ®ÂàÜÔºâ
      run: |
        sudo mkdir -p /overlay/lower
        sudo mkdir -p /mnt/overlay/upper
        sudo mkdir -p /mnt/overlay/work
        # ‰∏ãÈù¢1Ë°åÂéªÈô§OverlayÈúÄË¶ÅËøòÂéüÂà∞ ÂàùÂßãÂåñÁéØÂ¢É‰∏≠
        sudo mkdir -p /workdir
        sudo chmod 777 /overlay/lower
        sudo chmod 777 /mnt/overlay/upper

    - name: ÊåÇËΩΩ OverlayFS ÂêàÂπ∂ÂàÜÂå∫ÔºàOverlayÈÉ®ÂàÜÔºâ
      run: |
        sudo mount -t overlay overlay \
         -o rw,lowerdir=/overlay/lower,upperdir=/mnt/overlay/upper,workdir=/mnt/overlay/work /workdir
        mount | grep overlay

    - name: ËÆæÁΩÆ /workdir ÊùÉÈôêÔºàOverlayÈÉ®ÂàÜÔºâ
      run: |
        # ‰∏ãÈù¢1Ë°åÂéªÈô§OverlayÈúÄË¶ÅËøòÂéüÂà∞ ÂàùÂßãÂåñÁéØÂ¢É‰∏≠
        sudo chown $USER:$GROUPS /workdir

    - name: Ê£ÄÊü•Á©∫Èó¥‰ΩøÁî®ÊÉÖÂÜµÔºàOverlayFSÊòØÂê¶ÁîüÊïàÔºâ
      if: (!cancelled())
      run: df -hT

    - name: ÂÖãÈöÜÊ∫êÁ†Å
      working-directory: /workdir
      run: |
        git clone $REPO_URL --depth 1 -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

        cd ./openwrt/ && echo "WRT_HASH=$(git log -1 --pretty=format:'%h')" >> $GITHUB_ENV

        # GitHub Action ÁßªÈô§ÂõΩÂÜÖ‰∏ãËΩΩÊ∫ê
        PROJECT_MIRRORS_FILE="./scripts/projectsmirrors.json"
        if [ -f "$PROJECT_MIRRORS_FILE" ]; then
          sed -i '/.cn\//d; /tencent/d; /aliyun/d' "$PROJECT_MIRRORS_FILE"
        fi

    - name: Ê£ÄÊü•ÁºìÂ≠ò
      id: check-cache
      uses: actions/cache@main
      with:
        key: rockchip-${{env.REPO_BRANCH}}-${{env.WRT_HASH}}
        restore-keys: rockchip-${{env.REPO_BRANCH}}
        path: |
          ./openwrt/.ccache
          ./openwrt/staging_dir/host*
          ./openwrt/staging_dir/tool*

    - name: ÂºÄÂêØCCACHEÈÖçÁΩÆ
      run: |
        echo 'CONFIG_DEVEL=y' >> openwrt/.config
        echo 'CONFIG_CCACHE=y' >> openwrt/.config

    - name: Êõ¥Êñ∞ÁºìÂ≠ò
      run: |
        if [ -d "./openwrt/staging_dir" ]; then
          find "./openwrt/staging_dir" -type d -name "stamp" -not -path "*target*" | while read -r DIR; do
            find "$DIR" -type f -exec touch {} +
          done

          mkdir -p ./openwrt/tmp && echo "1" > ./openwrt/tmp/.build

          echo "toolchain skiped done!"
        else
          echo "caches missed!"
        fi

        if ${{steps.check-cache.outputs.cache-hit != 'true'}}; then
          CACHE_LIST=$(gh cache list --key "rockchip-$REPO_BRANCH" | cut -f 1)
          for CACHE_KEY in $CACHE_LIST; do
            gh cache delete $CACHE_KEY
          done

          echo "caches cleanup done!"
        fi

    - name: ÂÆâË£Ö feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: ÂØºÂÖ•Ë°•‰∏ÅÂíåÈÖçÁΩÆ & ÊâßË°åËÑöÊú¨
      run: |
        [ -d files ] && mv files openwrt/files || echo "files not found"
        [ -f $PLATFORM_FILE ] && cat $PLATFORM_FILE >> openwrt/.config
        [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
        [ -f $CONFIG_5G ] && cat $CONFIG_5G >> openwrt/.config
        chmod +x $RUST_SH && $RUST_SH
        cd openwrt
        chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
        chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
        chmod +x $GITHUB_WORKSPACE/$INSTALL5G_SH && $GITHUB_WORKSPACE/$INSTALL5G_SH
        chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH

    - name: ‰∏ãËΩΩÊñá‰ª∂
      run: |
        cd openwrt
        make defconfig
        make download -j8 V=10
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Á©∫Èó¥‰ΩøÁî®ÊÉÖÂÜµÔºàÁºñËØëÂâçÔºâ
      if: (!cancelled())
      run: df -hT

    - name: ÁºñËØëÂõ∫‰ª∂
      id: compile
      run: |
        cd openwrt
        make defconfig
        echo -e "$(nproc) thread compile"
        make -j$(($(nproc)+1)) || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Á©∫Èó¥‰ΩøÁî®ÊÉÖÂÜµÔºàÁºñËØëÂç†Áî®Ôºâ
      if: (!cancelled())
      run: df -hT

    - name: ‰∏ä‰º† bin ÁõÆÂΩï
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: Êï¥ÁêÜÊñá‰ª∂
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf *.bin
        rm -rf *.buildinfo 
        rm -rf *.json 
        rm -rf *.manifest 
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Âõ∫‰ª∂ÈáçÂëΩÂêç
      if: steps.organize.outputs.status == 'success' && !cancelled()
      shell: bash
      run: |
        cd openwrt/bin/targets/*/*
        for file in *rockchip-armv8-*.gz; do
          new_name=$(echo "$file" | sed 's/rockchip-armv8-//')
          mv -v "$file" "$new_name"
        done

    - name: ‰∏ä‰º†Âõ∫‰ª∂ÁõÆÂΩï
      uses: actions/upload-artifact@main
      if: env.UPLOAD_FIRMWARE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: ÁîüÊàêÂèëÂ∏ÉÊ†áÁ≠æ
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        VERSION1="${REPO_BRANCH#*-}"
        echo -e "üéâ RockchipÂπ≥Âè∞\n‚úÖ ${VERSION1} Ê∫êÁ†Å\n‚ùóÔ∏è ipÂú∞ÂùÄ : 192.168.8.1" >> release.txt
        echo "release_tag=$(date +"%Y.%m.%d-${VERSION1}_rockchip")" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT

    - name: ‰∏ä‰º†Âõ∫‰ª∂Âà∞ÂèëÂ∏É
      uses: softprops/action-gh-release@master
      if: steps.tag.outputs.status == 'success' && !cancelled()
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
